# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 21:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Handover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('claimed', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('support_level', models.CharField(choices=[('Enterprise', 'Enterprise'), ('Business', 'Business'), ('Developer', 'Developer')], max_length=10)),
                ('sev_level', models.CharField(choices=[('5', '5'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1)),
                ('engine', models.CharField(choices=[('MySQL', 'MySQL'), ('SQL Server', 'SQL Server'), ('Aurora', 'Aurora'), ('MariaDB', 'MariaDB'), ('PostgreSQL', 'PostgreSQL'), ('Redshift', 'Redshift'), ('DMS', 'DMS')], max_length=10)),
                ('case_link', models.URLField(max_length=100)),
                ('related_item1', models.URLField(blank=True, max_length=100)),
                ('related_item2', models.URLField(blank=True, max_length=100)),
                ('related_item3', models.URLField(blank=True, max_length=100)),
                ('attachment', models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/')),
                ('notes', models.TextField()),
                ('from_region', models.CharField(choices=[('SEA', 'SEA'), ('SYD', 'SYD'), ('DFW', 'DFW'), ('IAD', 'IAD'), ('CPT', 'CPT'), ('DUB', 'DUB')], default='SEA', max_length=3)),
                ('to_region', models.CharField(choices=[('SEA', 'SEA'), ('SYD', 'SYD'), ('DFW', 'DFW'), ('IAD', 'IAD'), ('CPT', 'CPT'), ('DUB', 'DUB')], default='SYD', max_length=3)),
                ('status', models.CharField(choices=[('Active (Action Needed)', 'Active (Action Needed)'), ('Pending Customer Response', 'Pending Customer Response'), ('Pending Amazon Response (TT)', 'Pending Amazon Response (TT)')], default='Active (Action Needed)', max_length=15)),
                ('last_updated', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('current_owner', models.CharField(blank=True, max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
