# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handover_items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handover',
            name='status',
            field=models.CharField(choices=[('Active (Action Needed)', 'Active (Action Needed)'), ('Pending Customer Response', 'Pending Customer Response'), ('Pending Amazon Response (TT)', 'Pending Amazon Response (TT)'), ('Completd', 'Completed')], default='Active (Action Needed)', max_length=15),
        ),
    ]
