# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handover_items', '0005_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='handover',
            name='owner_hist',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
