# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handover_items', '0006_handover_owner_hist'),
    ]

    operations = [
        migrations.AddField(
            model_name='primary',
            name='primary_deny_notes',
            field=models.TextField(blank=True),
        ),
    ]
