# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 23:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handover_items', '0007_primary_primary_deny_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='primary',
            old_name='primary_deny_notes',
            new_name='primary_notes',
        ),
    ]
