# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handover_items', '0008_auto_20170519_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primary',
            name='primary_notes',
        ),
        migrations.AddField(
            model_name='handover',
            name='primary_notes',
            field=models.TextField(blank=True),
        ),
    ]
