# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handover_items', '0010_auto_20170522_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='handover',
            old_name='primary_notes',
            new_name='primary_approval_notes',
        ),
        migrations.AddField(
            model_name='handover',
            name='primary_denial_notes',
            field=models.TextField(blank=True),
        ),
    ]
